# Generated by Django 4.0.4 on 2022-04-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_date',
        ),
    ]
